### ISSUE TITLE
"Minimize" mode

### ISSUE THREAD

**Issue by lkraav** [ibericode/boxzilla-wp#87]
I'm looking to replicate https://docs.hotjar.com/docs/how-do-hotjar-polls-work Hotjar widget dynamics with boxzilla.

There would be some kind of a px value X for "minimized" mode control element. So "close" would not completely hide the box anymore, but transition to `max-height: X`.

When minimized once (cookie is set), box could use this info to start in minimized mode from thereafter.

Automatic focus to form inputs inside the box needs to be disabled, because autofocus moves the field into the viewport of the limited `max-height`, creating confusion.

@dannyvankooten what are your thoughts on what the easiest way for this is? It looks like I'd have to write my own custom `Box.prototype.toggle` function. How would I assign this to the box?

Is this really a https://github.com/ibericode/boxzilla.js issue instead?

**Comment by lkraav** [comment]
Should `Animator` be exposed at `window` member? Makes it easier to use from custom override functions.

**Comment by lkraav** [comment]
I implemented this without `Animator` for now. Override logic is quite tricky, because have to account for all sorts of parameter combinations, but it works nicely. Upstream could probably augment a few things to make this sort of thing easier, I'll send a debrief later.

**Comment by dannyvankooten** [comment]
Hey @lkraav,

Nice, glad to hear you git all working already. I'm a little hesitant to add such a thing to Boxzilla itself because of the styling issues it would introduce (people use Boxzilla for so many different things) but I'd love to hear what we can do to make this easier.

Right now we're pretty much referring people to [MailChimp Top Bar](https://wordpress.org/plugins/mailchimp-top-bar/) for a much more constrained top or bottom bar which stays partially visible when minimized.

Autofocus will be removed in today's update, it was causing more issues on mobile browsers & seems a bit obtrusive anyway.

**Comment by lkraav** [comment]
Looks like competition is trying to do something similar to this idea: https://wordpress.org/plugins/holler-box/

**Comment by arnelap** [comment]
Another request for this: https://secure.helpscout.net/conversation/465095310/12253?folderId=491449

**Comment by lkraav** [comment]
We have it successfully running at https://gotravel.ee

You're welcome to use the implementation as a prototype. See https://gotravel.ee/wp-content/themes/gotravel/script.js search for "boxzilla minimized mode".

**Comment by arnelap** [comment]
@lkraav I've copied the code here: https://github.com/ibericode/mc4wp-snippets/blob/master/misc/boxzilla-minimize.js

Thanks for sharing!

**Comment by lkraav** [comment]
@arnelap I can't recall whether https://github.com/ibericode/boxzilla.js/issues/14#issuecomment-312223249 affected this or not, as we've stayed put on 3.1.13. I'll get back to you about this once we have time to upgrade and take a look.

**Comment by ofmarconi** [comment]
Hello,

I did not understand how to install this Snippets, could you explain me better?

Thank you

**Comment by ofmarconi** [comment]
I managed,

But it is not hiding when you click on the X, do you have to implement with CSS? Or just stick this JS?
Only change from X to Arrow.

@lkraav do you have any idea how I can animate the entrance and exit of this box?

**Comment by lkraav** [comment]
@ofmarconi good point, there's definitely CSS involved, I forgot about that. Check the LESS below, and try to replace some of the used variables with your own values where necessary.

```less
.boxzilla.boxzilla-vota-uhendust { @border-radius: 0.25em; @font-size: 0.75rem; background-color: transparent !important; border-top-left-radius: @border-radius; border-top-right-radius: @border-radius; box-shad
ow: 0 0.5em 0.5em #0006; left: 0; margin: auto; padding: 0; right: 0; transform: translateZ(0); z-index: 2147483647 /* #scroll-up */;

    &.boxzilla-bottom-right {
        @media @small { left: auto; right: @grid-unit; }
    }

    a { border-bottom: none; color: white; }

    .boxzilla-close-icon { background-color: @orange; color: @white; font-size: 1em; opacity: 1; padding: @font-size ( @font-size * 1.33 );
        &:active { background-color: white; color: @orange; }
    }

    .boxzilla-content { background-color: black; }

    .mobile-safari & { position: fixed };

}
```
